// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "C:\\Users\\lukes\\cortextos\\dist\\daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "C:\\Users\\lukes\\cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "C:\\Users\\lukes\\.cortextos\\default",
        CTX_FRAMEWORK_ROOT: "C:\\Users\\lukes\\cortextos",
        CTX_PROJECT_ROOT: "C:\\Users\\lukes\\cortextos",
        CTX_ORG: process.env.CTX_ORG || "sitesmith-agency",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "C:\\Users\\lukes\\cortextos\\dashboard\\node_modules\\next\\dist\\bin\\next",
      args: "dev",
      cwd: "C:\\Users\\lukes\\cortextos\\dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
